# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder "../", "/vagrant", id: "vagrant-root", type: "nfs"
  config.vm.box = "bento/freebsd-11.1"
  config.ssh.shell = "sh"
  config.vm.base_mac = "080027D14C66"
  config.vm.network "private_network", ip: "172.30.1.5"
  config.vm.provision "shell", privileged: true, path: "init.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    vb.gui = true
  end
end
